# General Jekyll Config
pygments: true
url: http://wiki.bananafish.in
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

markdown:      rdiscount
markdown_ext:  markdown,mkd,mkdn,md

rdiscount:
  extensions: []

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Google Analytics key, leave blank to ignore
  #google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
